# Generated by Django 3.1 on 2020-08-09 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodtaskerapp', '0006_driver_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='foodtaskerapp.customer'),
        ),
        migrations.AlterField(
            model_name='order',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='foodtaskerapp.driver'),
        ),
        migrations.AlterField(
            model_name='order',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='foodtaskerapp.restaurant'),
        ),
        migrations.AlterField(
            model_name='orderdetails',
            name='meal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='foodtaskerapp.meal'),
        ),
        migrations.AlterField(
            model_name='orderdetails',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='order_details', to='foodtaskerapp.order'),
        ),
    ]
